### ISSUE TITLE
N2KD crashing after time

### ISSUE THREAD

**Issue by ump-onwatch** [canboat/canboat#196] opened 2020-06-02 02:10 UTC
I have the n2kd server running and am retrieving the data via node-red TCP node. after a random amount of time the n2kd server crashes with error:
Input line on stream 7 too long:

**Comment by keesverruijt** [comment] 2020-08-09 10:28
Can you please provide a better reproduction case? What is stream 7 in your case? 
You can run`n2kd` in debug mode (`-d`) to see this in more detail.
If it happens within a reasonable time you could run `strace` on the n2kd process.

**Comment by keesverruijt** [comment] 2022-10-18 14:05
Closing due to no updates, please re-open if you can reproduce with current version.

**Closed by keesverruijt** 2022-10-18 14:05 UTC
Labels: need sample data, verification
